name: hybrid_logger
description: "Hybrid Logger, Gives different Log tools for development, such as common debug logs, stacktrace, http calls, etc."
version: 1.0.3
homepage: https://rudo.es/
repository: https://github.com/rudoapps/hybrid-logger.git
issue_tracker: https://github.com/rudoapps/hybrid-logger/issues
topics:
  - logs
  - logger
  - http
  - stacktrace
  - debug

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15
